### ISSUE TITLE
Alternate Gmail Address: @colgate.edu, @hamilton.edu, @wellesley.edu

### ISSUE THREAD

**Issue by dseaton** [mitodl/xanalytics#5]
Colgate, Hamilton, and Wellesley all use gmail as their enterprise email service. Would be a better option if they could use those addresses to manage access to the dashboard.

**Comment by musixhine** [comment]
found the way to make it work:

1. Download/Install Google App Engine Launcher on your Mac 
2. Make edit on you Mac and use the Google App Engine Launcher to publish it.
3. It will popup a browser and ask you to login.

I’ve done this and it’s working with my wellesley gmail

**Comment by musixhine** [comment]
he way to make it work:

1. Download/Install Google App Engine Launcher on your Mac 
2. Make edit on you Mac and use the Google App Engine Launcher to publish it.
3. It will popup a browser and ask you to login.

I’ve done this and it’s working with my wellesley gmail
